### ISSUE TITLE
$0 no longer resolves to the hovered file

### ISSUE THREAD

**Issue by kyletruong** [AnirudhG07/custom-shell.yazi#4] opened 2024-08-11 06:40 UTC
After adding this plugin, the `$0` shell variable no longer resolves to the hovered file. It resolves to `zsh` in my case, which is my custom shell.

**Comment by AnirudhG07** [comment] 2024-08-11 15:00
Can you share what exactly you are giving into the input? I have been meaning to look into this, just didnt do it yet

**Comment by kyletruong** [comment] 2024-08-12 18:08
@AnirudhG07 Yes, for example when I run `nvim $0` it opens a new file called `zsh` instead of opening the currently hovered file.

<img width="1774" alt="Screenshot 2024-08-12 at 11 03 42 AM" src="https://github.com/user-attachments/assets/777f0b27-a6fa-405c-9dfd-d1e8e18511e1">

<img width="1774" alt="Screenshot 2024-08-12 at 11 04 23 AM" src="https://github.com/user-attachments/assets/acae0e45-f12b-43d6-b7c5-b66a6e4c4aff">

**Comment by AnirudhG07** [comment] 2024-08-13 09:28
I see. fine ill work on fixing this issue.
If you would like to contribute, you are very welcome to(do inform me, if you are doing it)!
It would take a week-ish, since i am bit busy these days. i hope its fine with you

**Comment by uxfion** [comment] 2024-09-07 16:18
How is the progress? I am also encountering this issue now, unable to parse `$@` after using this plugin.

## reproduce

- select 2 files and use the default yazi block shell `:`

```
echo $@
```
it will echo the path of two files.

- select 2 files and use custom-shell.yazi, aka `plugin custom-shell --args=auto`
```
echo $@
```
it echo nothing

---

I think the problem lies in `sh -c 'zsh -ic "echo $@; exit"'`, where `$@` is not being interpreted correctly.

It may relate to https://github.com/sxyazi/yazi/issues/1524

I don't know how to handle it.

**Comment by AnirudhG07** [comment] 2024-09-07 16:27
Yes. zsh or any shell does not interpret `$0` as yazi does. I will work on it. I'll have to look into how to get it to work. Give me some more time

**Comment by uxfion** [comment] 2024-09-07 18:23
```
local selected_or_hovered = ya.sync(function()
	local tab, paths = cx.active, {}
	for _, u in pairs(tab.selected) do
		paths[#paths + 1] = tostring(u)
	end
	if #paths == 0 and tab.current.hovered then
		paths[1] = tostring(tab.current.hovered.url)
	end
	return paths
end)

return {
  entry = function()
    ya.manager_emit("escape", { visual = true })
    local urls = selected_or_hovered()
    local paths = table.concat(urls, " ")

    local value, event = ya.input {
      title = "Zsh shell:",
      position = { "top-center", y = 3, w = 40 },
    }
    if event == 1 then
      if value:match("%s$@$") then
        value = value:gsub("%s$@$", " " .. paths)
      end
      ya.notify({
        title = "exec",
        content = "zsh -ic " .. ya.quote(value .. "; exit", true),
        -- content = table.concat(urls, " "),
        timeout = 8,
      })

      ya.manager_emit("shell", {
        "zsh -ic " .. ya.quote(value .. "; exit", true),
        block = true,
        confirm = true,
      })
    end
  end,
}
```
Take a look at this. It might be a bit clumsy, but it works. Forcibly replace `$@` with selected_or_hovered. Perhaps this is unacceptable for this repo.

**Comment by AnirudhG07** [comment] 2024-09-07 18:57
I was also thinking in similar direction, but this has to carefully applied so that it works properly with pre-added configs. Thanks for the snippet though, might come in handy.

**Comment by sxyazi** [comment] 2024-09-08 03:12
I think you can just `string.format('zsh -ic %s "$0" "$@"', ya.quote(value .. '; exit', true))`

**Comment by uxfion** [comment] 2024-09-08 03:31
‌‌I think this fork [KKV9/shell.yazi](https://github.com/KKV9/shell.yazi) from you perfectly solves the problem 😂.

The power of the plugin community is strong and immeasurable; you can always find better plugins. If you can't find a better plugin, you can directly modify it yourself. 

@sxyazi You are really smart to hand over the complicated customized plugins to the community. 💕 Thank you for the endless convenience your yazi has brought me.

If possible, it can be added to https://yazi-rs.github.io/docs/resources#shell

**Comment by AnirudhG07** [comment] 2024-12-31 10:27
Shifted to #11! Closing this.

**Closed as completed by AnirudhG07** 2024-12-31 10:27 UTC

**Comment by ameknite** [comment] 2025-01-28 00:53
yeah also happened to me, it doesn't work. I was lucky that for my use case, I need all the content inside the directory so I just replaced it for "./"
